# Generated by Django 3.1.6 on 2021-03-10 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('university', models.CharField(choices=[('University of Exeter', 'University of Exeter'), ('Test uni', 'Test uni')], max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=50)),
                ('points', models.PositiveIntegerField(default=0)),
                ('studying_until', models.DateTimeField(blank=True, null=True)),
                ('share_tables', models.BooleanField(default=True)),
                ('tasks_set_today', models.PositiveIntegerField(default=0)),
                ('next_possible_set', models.DateField(blank=True, null=True)),
                ('student_tasks_completed', models.PositiveIntegerField(default=0)),
                ('next_possible_complete', models.DateField(blank=True, null=True)),
                ('facebook', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CafeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('date_set', models.DateField(auto_now_add=True)),
                ('task_content', models.TextField(max_length=4000)),
                ('points', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30')], default=0)),
                ('recurring_date', models.DateField(blank=True, null=True)),
                ('recurrence_interval', models.CharField(choices=[('n', 'NONE'), ('d', 'DAILY'), ('w', 'WEEKLY')], max_length=1)),
                ('no_of_repeats', models.PositiveIntegerField(default=0)),
                ('max_repeats', models.PositiveIntegerField(default=0)),
                ('completed_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.cafetable')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Table (general)', 'Table (general)'), ('Task', 'Task'), ('Messages', 'Messages'), ('Other', 'Other')], max_length=50)),
                ('detail', models.CharField(max_length=250)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.cafetable')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(choices=[(1, 'Award'), (2, 'Points'), (3, 'Task')])),
                ('text_preview', models.CharField(blank=True, max_length=90)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('table_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_post', to='app.cafetable')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('message_content', models.TextField(max_length=4000)),
                ('total_upvotes', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('message_upvote', models.ManyToManyField(related_name='message_upvote', to=settings.AUTH_USER_MODEL)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.cafetable')),
            ],
        ),
        migrations.AddField(
            model_name='coffeeuser',
            name='cafe_table_ids',
            field=models.ManyToManyField(blank=True, to='app.CafeTable'),
        ),
    ]
