# Generated by Django 3.1.6 on 2021-02-16 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('course', models.CharField(max_length=50)),
                ('avatar_url', models.FilePathField(path='/img')),
                ('points', models.PositiveIntegerField(default=0)),
                ('cafe_table_ids', models.ManyToManyField(to='app.CafeTable')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.PositiveIntegerField()),
                ('task_date', models.DateTimeField(auto_now_add=True)),
                ('task_content', models.TextField(max_length=4000)),
                ('completed_by', models.ManyToManyField(to='app.CoffeeUser')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='app.coffeeuser')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='app.cafetable')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField()),
                ('message_date', models.DateTimeField(auto_now_add=True)),
                ('message_content', models.TextField(max_length=4000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.coffeeuser')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='app.cafetable')),
            ],
        ),
    ]
