# Generated by Django 3.0.1 on 2021-03-01 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message_message_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='total_upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_upvote',
            field=models.ManyToManyField(related_name='message_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
