# Generated by Django 3.1.6 on 2021-02-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210218_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafetable',
            name='university',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffeeuser',
            name='cafe_table_ids',
            field=models.ManyToManyField(blank=True, to='app.CafeTable'),
        ),
        migrations.AlterField(
            model_name='coffeeuser',
            name='course',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coffeeuser',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
