# Generated by Django 3.1.6 on 2021-03-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coffeeuser_studying_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeuser',
            name='tasks_set_today',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
