# Generated by Django 3.1.6 on 2021-03-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coffeeuser_studying_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeuser',
            name='share_tables',
            field=models.BooleanField(default=True),
        ),
    ]
