# Generated by Django 3.1.6 on 2021-02-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210219_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeuser',
            name='university',
            field=models.CharField(choices=[('University of Exeter', 'University of Exeter'), ('Test uni', 'Test uni')], max_length=50),
        ),
    ]
