# Generated by Django 3.1.6 on 2021-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_coffeeuser_share_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffeeuser',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='coffeeuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coffeeuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coffeeuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
