# Generated by Django 3.1.6 on 2021-03-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_coffeeuser_tasks_set_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeuser',
            name='next_possible_set',
            field=models.DateField(blank=True, null=True),
        ),
    ]
