# Generated by Django 3.1.6 on 2021-02-20 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_task_completed'),
        ('app', '0005_auto_20210220_0212'),
    ]

    operations = [
    ]
