# Generated by Django 3.1.6 on 2021-02-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20210220_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_id',
        ),
    ]
