# Generated by Django 3.1.6 on 2021-03-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_coffeeuser_next_possible_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30')], default=0),
        ),
    ]
