# Generated by Django 3.1.6 on 2021-03-07 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210305_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Table (general)', 'Table (general)'), ('Task', 'Task'), ('Messages', 'Messages'), ('Other', 'Other')], max_length=50)),
                ('detail', models.CharField(max_length=250)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.cafetable')),
            ],
        ),
    ]
