# Generated by Django 3.1.6 on 2021-03-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210304_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeuser',
            name='next_possible_complete',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coffeeuser',
            name='student_tasks_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
