# Generated by Django 3.1.6 on 2021-03-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210305_0943'),
        ('app', '0008_auto_20210305_0557'),
    ]

    operations = [
    ]
