# Generated by Django 3.1.6 on 2021-03-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20210306_1116'),
        ('app', '0007_report'),
    ]

    operations = [
    ]
