# Generated by Django 3.1.6 on 2021-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20210306_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_last_set',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='no_of_repeats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_interval',
            field=models.PositiveIntegerField(choices=[('d', 'DAILY'), ('w', 'WEEKLY')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
