# Generated by Django 3.1.6 on 2021-03-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210308_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='recurrence_interval',
            field=models.CharField(choices=[('n', 'NONE'), ('d', 'DAILY'), ('w', 'WEEKLY')], max_length=1),
        ),
    ]
