# Generated by Django 3.1.6 on 2021-03-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210308_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_repeats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
