# Generated by Django 3.1.6 on 2021-03-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_task_max_repeats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_last_set',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
