# Generated by Django 3.1.6 on 2021-03-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210308_1721'),
        ('app', '0010_merge_20210308_1316'),
    ]

    operations = [
    ]
