# Generated by Django 3.1.7 on 2021-03-08 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='table_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_post', to='app.cafetable'),
        ),
    ]
